### ISSUE TITLE
in link

### ISSUE THREAD

**Issue by reslear** [jo-o-jj/atom-timestamp#1]
prefix **\?d=?**
suffix **$**
format **YYYY-MM-DD_HH:mm:ss**
```@import "base/global-base.css?2017-05-07_22:06:11";```

not work, please help from work

**Comment by jo-o-jj** [comment]
prefix/suffix must be regular expression pattern.
atom-timestamp updates timestamps between prefix and suffix.

by default, atom-timestamp only works in comment sentences, not in whole CSS code.
so you also need `Scope Selector` option as below:

Timestamp Prefix: `^@import "[^"]+\?`
Timestamp Suffix: `";$`
Timestamp Formats: `YYYY-MM-DD_HH:mm:ss`
Scope Selector: `^comment\b|css|plain\.text`

**Comment by reslear** [comment]
working, thank you, friend!
and please give link to documentation on Scope Selector in Atom

**Comment by jo-o-jj** [comment]
documentation about scope in syntax:
http://flight-manual.atom.io/behind-atom/sections/scoped-settings-scopes-and-scope-descriptors/

and you can easily find scope names on cursor by using `Editor: Log Cursor Scope` in command palette.

**Comment by jo-o-jj** [comment]
just updated README. thanks
